# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://therealchisco.github.io
title: 'RMS: Restaurant Menu System'
email: restaurant.menu.system@gmail.com
author: Grupo zero
description: > # "Write an awesome description for your new site here. 
  RMS es el sistema de menús digitales para restaurantes más simple, eficiente y económico
copyright: 'Copyright &copy; 2019 RMS. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/ResMenuSystem 
